server.port: 8762

endpoint-config:
  allowed-origins:
  - http://localhost:3000
  - http://localhost:5000
  - http://localhost:8760
  - http://localhost:8761
  allowed-methods:
  - HEAD
  - GET
  - PATCH
  - POST
  - PUT
  - DELETE

spring:
  application.name: enduscan-service
  #jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/z_endu?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}

eureka:
  instance.leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}